### PR TITLE
[Docs] Update assistant-setup-inbound.mdx

### PR DESCRIPTION
**Pull request by ram-sharma**
[Docs] small fix - fix broken link to provider keys

Link to page with broken link: https://docs.vapi.ai/quickstart/phone/inbound#set-your-openai-provider-key-optional

> Before we proceed, we can set our [provider key](https://docs.vapi.ai/quickstart/phone/customization/provider-keys) for OpenAI (this is just your OpenAI secret key).

### CODE REVIEW

**Comment by ram-sharma** [comment]
ignore this, for some reason the tests failed, will investigate

**Comment by ram-sharma** [comment]
Ok , i tested this on local fern dev environment and it seems to work as expected, I still see these errors despite changing anything, I will re-open the pull request for now.

**Comment by ram-sharma** [comment]
this is ready for review!

**Comment by sahilsuman933** [comment]
Thank you for the PR!

**Pull request merged**
